version: '3.8'

services:
  waf:
    build: .
    container_name: bitphantom-waf
    ports:
      - "3001:3001"
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - WAF_MODE=block
      - ENABLE_AI=true
      - LOG_LEVEL=info
      - RATE_LIMIT_WINDOW=60000
      - RATE_LIMIT_MAX=100
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config:ro
    restart: unless-stopped
    networks:
      - waf-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (r) => {r.statusCode === 200 ? process.exit(0) : process.exit(1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  redis:
    image: redis:7-alpine
    container_name: bitphantom-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - waf-network
    restart: unless-stopped
    command: redis-server --appendonly yes

networks:
  waf-network:
    driver: bridge

volumes:
  redis-data: